import type { Metadata } from "next";
import { Inter, DM_Sans } from "next/font/google";
import "./globals.css";
import Footer from "../components/footer/Footer";
import Navbar from "../components/navbar/Navbar";

const inter = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Superstar Mentors",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          {children}
         </main>
      </body>
    </html>
  );
}
